name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho


permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: micro-todo-ui-api
      IMAGE_TAG: v2
      ACR_NAME: acrdevtodoproject0214
      ACR_LOGIN_SERVER: acrdevtodoproject0214.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 94aa6efd-4270-4181-a7aa-2ba17b2c6ca5
          tenant-id: b37dfdd9-3fd0-4040-8a71-c68b0a34b98e
          subscription-id: 925c3861-e9e3-43c1-8a0c-d6faefd4a05a

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
           docker buildx build -t $IMAGE_NAME:$IMAGE_TAG -f MicroTodoUI/Dockerfile MicroTodoUI

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
